### ISSUE TITLE
Punctuation at end of bold, italic

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/INM#6]
Generally, punctuation at the end of bold and italic markup should be OUTSIDE the markup:
Bold: `{@X,@} -> {@X@},`.  And similarly for italics: `{%X,%} -> {%X%},`

Such changes were made for the punctuatiion: period, comma, semicolon, colon.
For Bold: 34000 instances
For Italic: 44000 instances.

**Comment by funderburkjim** [comment]
## parenthetical italics
```
22609 matches in 18003 lines for "{%(" in buffer: inm.txt  changed to ({%
22978 matches in 18304 lines for ")%}" in buffer: inm.txt changed to %})
```
Common example:
OLD:
{%(a)%}
NEW:
({%a%})
```

**Comment by gasyoun** [comment]
> Such changes were made for the punctuatiion: period, comma, semicolon, colon.

Would love to see the list of all the regexes applied or the PY code.

**Comment by funderburkjim** [comment]
I did these within Emacs.
These particular changes don't require regexes - simple string replacements suffice.
For example:  `,%}` -> `%},`.    Other changes similar.

**Comment by gasyoun** [comment]
> These particular changes don't require regexes - simple string replacements suffice.

I mean the issue is far more general than just INM. So I try to understand what way to replicate it.
