### ISSUE TITLE
Remove `<div n="lb">`

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/INM#7]
In line with the general principle regarding [line break markup](https://github.com/sanskrit-lexicon/csl-devanagari/issues/26#issuecomment-924512081) in the Cologne digitizations, the `<div n="lb"/>` markup
should be removed in inm.txt.

While this is simple  (just a global change-replace),  I want to maintain there to be no change in the current displays, i.e., the html displays should maintain the same lines as inm.txt.    One way to do this is to reinsert the line breaks into the xml code (by modifying the 'make_xml.py' program for inm.txt.

**Comment by funderburkjim** [comment]
This change implemented, per the two commits noted above.

**Comment by gasyoun** [comment]
> I want to maintain there to be no change in the current displays

There will be fun, when we'll decide to unite the UI.
